# Permalinks
permalink:              /:title
relative_permalinks:    true

# Setup
title:                  'UVW.no'
tagline:                'Delte meninger'
url:                    http://www.uvw.no
paginate:               1
paginate_path:          'side:num'
baseurl:                ''
author:
  name:                 Glenn M. Hinderaker
  url:                  https://twitter.com/gmhinderaker
  email:                glenn@hinderaker.com

# Assets
sass:
  sass_dir:             _scss
  style:                :compressed

# Custom vars
version:                1.0.0
github:
  repo:                 https://github.com/uvwnett/uvwnett.github.com.git

# Pages
pages_list:
  Arkivet:              '/arkiv/'
  RSS:                  '/atom.xml'